notify:
    runs-on: ubuntu-latest
    needs: deploy
    env:
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHAT_IDS: ${{ secrets.TG_CHAT_IDS }} 
      PAGE_URL: ${{ needs.deploy.outputs.page_url }} 
    steps:
      - name: Check Telegram variables
        run: |
          if [ -z "${TG_BOT_TOKEN}" ]; then
            echo "❌ TG_BOT_TOKEN не задано!"
            exit 1
          fi
          if [ -z "${TG_CHAT_IDS}" ]; then
            echo "❌ TG_CHAT_IDS не задано!"
            exit 1
          fi
          if [ -z "${PAGE_URL}" ]; then
            echo "❌ Не вдалося отримати PAGE_URL з кроку deploy!"
            exit 1
          fi
          
      - name: Notify Telegram on Success (Silently)
        if: success()
        run: |
          MSG=$(printf "✅ Сайт успішно оновлено!\n\n%s" "${PAGE_URL}")
          
          echo "${TG_CHAT_IDS}" | tr ',' '\n' | while read -r CHAT_ID; do
            TRIMMED_CHAT_ID=$(echo "$CHAT_ID" | tr -d ' ')
            
            if [ -n "$TRIMMED_CHAT_ID" ]; then
              echo "Відправка ТИХОГО сповіщення до чату: $TRIMMED_CHAT_ID"
              
              # Створюємо JSON для кожного запиту
              JSON_PAYLOAD=$(cat <<EOF
{
  "chat_id": "${TRIMMED_CHAT_ID}",
  "text": "${MSG}",
  "disable_web_page_preview": false,
  "disable_notification": true
}
EOF
)
              
              # Надсилаємо запит
              curl -s -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" \
                -H "Content-Type: application/json" \
                -d "${JSON_PAYLOAD}"
            fi
          done